[build]
builder = "dockerfile"
dockerfilePath = "apps/backoffice/Dockerfile"

[deploy]
startCommand = "bun apps/backoffice/build/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
