[build]
builder = "dockerfile"
dockerfilePath = "apps/backoffice/Dockerfile"
watchPaths = ["apps/backoffice/**", "packages/**"]

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
